### ISSUE TITLE
Styling in About Us page

### ISSUE THREAD

**Issue by vanitashetty** [vanitashetty/Current-Weather#1]
The about us page is very simple. I think it need some more styling to the page like background image or like that. Also the background image is not getting displayed

![Screenshot 221931](https://github.com/vanitashetty/Current-Weather/assets/110151652/f827ca6d-7e04-45bd-88cb-784779d5caad)

**Comment by shubhamnimbalkkar** [comment]
Hello, I would like to work on this issue please assign me the task!

**Comment by vanitashetty** [comment]
@shubhamnimbalkkar yeah, feel free to work.
